version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "juan-miii"
  - package-ecosystem: "maven"
    directory: "/back"
    schedule:
      interval: "weekly"
    reviewers:
      - "juan-miii"
  - package-ecosystem: "npm"
    directory: "/front"
    schedule:
      interval: "weekly"
    reviewers:
      - "juan-miii"
