spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tennis_session_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: all.galeano.diaz@gmail.com
    password: ***REMOVED***
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
