spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        show_sql: false
  h2:
    console:
      enabled: true
      path: /h2-console

  mail:
    host: localhost
    port: 3025
    username: test
    password: test
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  logging:
    level:
      root: WARN
      org.hibernate: ERROR
      org.hibernate.type: ERROR
      org.hibernate.stat: ERROR
      org.hibernate.SQL: ERROR
      org.hibernate.type.descriptor.sql: ERROR
      org.springframework: WARN
      es.upm.tennis.tournament.manager: INFO